### ISSUE TITLE
Add prebuilt dll for win

### ISSUE THREAD

**Issue by mrx23dot** [miketlk/secp256k1-dll#1]

**Comment by miketlk** [comment]
Ganesh, thank you for creating this issue. The idea of the project is to help people building the DLL themselves or integrating this process in their project's build scripts. Publishing a pre-build binary would make me responsible for assuring the DLL is trustworthy. I think it makes more sense forwarding this request to the maintainers of [secp256k1-zkp](https://github.com/ElementsProject/secp256k1-zkp). I don't know if they have any plans for releasing official binaries.
So, if you don't mind, I'm closing this issue as non-relevant to my project goal.
